spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ensf480
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
